# Generated by Django 4.0.1 on 2022-01-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='description',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_description',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(default='N/A', upload_to='hotel/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_star',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='roomQuantity',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_title', models.CharField(max_length=100)),
                ('room_image', models.ImageField(upload_to='rooms/')),
                ('room_capacity', models.PositiveIntegerField()),
                ('room_avaibility', models.BooleanField(default=True)),
                ('room_description', models.TextField()),
                ('room_price', models.PositiveIntegerField()),
                ('room_discount_price', models.PositiveIntegerField()),
                ('available_date', models.CharField(max_length=150)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.hotel')),
            ],
        ),
    ]
